In [ ]:
"""
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

"""

In [ ]:
"""
Ans. Yes, there is a difference in the data type of variables list_ and array_list.

list_ is a Python list object that can contain elements of any data type, including strings, integers, floats, and other objects. On the other hand, array_list is a NumPy ndarray object that contains elements of a single data type, which is determined based on the input data.

"""

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))  # Output: <class 'list'>
print(type(array_list))  # Output: <class 'numpy.ndarray'>


<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [2]:
# Ans.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
"""
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

"""

In [1]:
# Ans.

import numpy as np

# create a list of mixed data types
list_ = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

# create a NumPy array of integers
array_list = np.array(object=list_, dtype=int)

# print the data types of each element in the list
for element in list_:
    print(type(element))

# print the data types of each element in the NumPy array
for element in array_list:
    print(type(element))


<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [ ]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# find the shape of the array
print("Shape of the array:", num_array.shape)

# find the size of the array
print("Size of the array:", num_array.size)


In [ ]:
"""
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]
"""


In [2]:
import numpy as np

# create a 3x3 NumPy array of zeros
zeros_array = np.zeros((3, 3))

print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
"""
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
"""


In [3]:
import numpy as np

# create a 5x5 identity matrix
identity_matrix = np.identity(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
